" Generated by vim-plug
" Tue Nov 16 08:09:02 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['YCM-Generator'].commit = '7c0f5701130f4178cb63d10da88578b9b705fbb1'
silent! let g:plugs['ale_yaml_linter'].commit = '535216b69f0db4c98e161766c877d012c57f5931'
silent! let g:plugs['aws-vim'].commit = 'c84d197a0eb9186f40c1740d29072f5fa6a4e6e3'
silent! let g:plugs['coc-fzf'].commit = '60828294b9ba846c78893389d4772021043d2fa1'
silent! let g:plugs['coc-neco'].commit = 'fe130c2c3b883f8b58f70f15bf36c73923faa3d9'
silent! let g:plugs['coc.nvim'].commit = '287c743c9f227fdf0e1db452bbb8ae3c5caffc36'
silent! let g:plugs['fzf'].commit = 'e4c3ecc57e99f4037199f11b384a7f8758d1a0ff'
silent! let g:plugs['fzf.vim'].commit = 'd6aa21476b2854694e6aa7b0941b8992a906c5ec'
silent! let g:plugs['gocode'].commit = 'eef10fdde96a12528a6da32f51bf638b2863a3b1'
silent! let g:plugs['neco-vim'].commit = 'ac084414cf1e0de86f5abaab6269b940806e8c6e'
silent! let g:plugs['nerdtree'].commit = 'eed488b1cd1867bd25f19f90e10440c5cc7d6424'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['nvim-web-devicons'].commit = 'f936ff3e1f9d58ec0caf0bd398e9675b54fe292e'
silent! let g:plugs['purify'].commit = 'f30fb7949c0144e5c8a4c56c6b0a77e9ca6849af'
silent! let g:plugs['space-vim-dark'].commit = 'd24c6c27b49c1ab49416a47d96979481281f53b5'
silent! let g:plugs['tagbar'].commit = 'b6669c7c9de542c53f2d19a806abb7610e9ef813'
silent! let g:plugs['ultisnips'].commit = '53e1921e3ef015ef658e540c0aa9c4835f9c18a6'
silent! let g:plugs['vim-classpath'].commit = '88a7e8a62d4603e79787cb381fc5cac562c29bb0'
silent! let g:plugs['vim-devicons'].commit = 'd16475cbd7d50664e3d9261951cd4415967c5c41'
silent! let g:plugs['vim-dirvish'].commit = 'f297b2effb0ec879f33a8539b9701d048d44f295'
silent! let g:plugs['vim-dirvish-git'].commit = '1d938c826503059660d89f186d2e8affc686a0e8'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-fireplace'].commit = 'c9a155b88d629221628937eadb64a3e87f8d82d9'
silent! let g:plugs['vim-github-dashboard'].commit = '8012a2016a9e39a50081c9d5db2deb09ae4a6010'
silent! let g:plugs['vim-go'].commit = 'f3ebf20e2c5dd672d55af26fdde6edb41971336b'
silent! let g:plugs['vim-multiple-cursors'].commit = '6456718e1d30b42c04b920c5413ca44f68f08759'
silent! let g:plugs['vim-projectionist'].commit = '438b58aab54624e554d71063a69ba3d1e1bfbc2f'
silent! let g:plugs['vim-snippets'].commit = '43ed873ba09ac2d71992e773c68c75c6b85686c7'
silent! let g:plugs['vim-which-key'].commit = '7e3819a91a7710ce561a9c11a22a82b9437a2533'
silent! let g:plugs['vista.vim'].commit = 'a0469c645dcbe4033b857da27d35491f39e2f776'

PlugUpdate!

